### ISSUE TITLE
Undefined symbol in convert_imageset

### ISSUE THREAD

**Issue by JarnoRFB** [conda-forge/caffe-feedstock#33]
I have a problem with the command line tools provided by caffe on Ubuntu 16.04
Doing 
```
$ conda create -n test python=3.6
$ source activate test
$ conda install caffe
$ convert_imageset
```

I get 
`convert_imageset: symbol lookup error: convert_imageset: undefined symbol: _ZN6google14FlagRegistererC1EPKcS2_S2_S2_PvS3_
`
The output of `$ c++filt _ZN6google14FlagRegistererC1EPKcS2_S2_S2_PvS3_` is 
`google::FlagRegisterer::FlagRegisterer(char const*, char const*, char const*, char const*, void*, void*)
`
The respective binary of `convert_imageset` is for me in `$CONDA_ROOT/envs/test/bin` 

Since many tutorials or training instructions for caffe nets rely on these tools it would be great if they would work out of the box with the conda install.

**Comment by jakirkham** [comment]
Could you please include the result of `conda env export` for the environment in question?

**Comment by JarnoRFB** [comment]
The output of `$ conda env export` is:

```
name: test
channels:
- defaults
dependencies:
- boost=1.61.0=py36_0
- caffe=1.0.0rc5=np112py36_0
- cycler=0.10.0=py36_0
- dbus=1.10.20=0
- decorator=4.1.2=py36_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- gflags=2.2.0=1
- glib=2.50.2=1
- glog=0.3.5=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- h5py=2.7.0=np112py36_0
- hdf5=1.8.17=2
- icu=54.1=0
- ipython=6.1.0=py36_0
- ipython_genutils=0.2.0=py36_0
- jbig=2.1=0
- jedi=0.10.2=py36_2
- jpeg=8d=2
- leveldb=1.20=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libprotobuf=3.2.0=0
- libtiff=4.0.6=2
- libxcb=1.12=1
- libxml2=2.9.4=0
- lmdb=0.9.21=0
- matplotlib=2.0.2=np112py36_0
- mkl=2017.0.3=0
- networkx=1.11=py36_0
- numpy=1.12.1=py36_0
- opencv=3.1.0=np112py36_1
- openssl=1.0.2l=0
- pandas=0.20.3=py36_0
- path.py=10.3.1=py36_0
- pcre=8.39=1
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pillow=3.4.2=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- protobuf=3.2.0=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- python-gflags=3.1.1=py36_0
- python-leveldb=0.194=py36_1
- pytz=2017.2=py36_0
- pywavelets=0.5.2=np112py36_0
- pyyaml=3.12=py36_0
- qt=5.6.2=2
- readline=6.2=2
- scikit-image=0.13.0=np112py36_0
- scipy=0.19.1=np112py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- snappy=1.1.6=0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- yaml=0.1.6=0
- zlib=1.2.11=0
- pip:
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.15
prefix: /work/miniconda/envs/test

```

**Comment by dougalsutherland** [comment]
Note that this recipe is only built for python 2.7, so you're actually using caffe from the default repositories.

**Comment by JarnoRFB** [comment]
So the version from this feedstock is only for Python 2.7? 
When I try to install it inside a Python 2 environment I get even more errors though...

For
```
$ conda create -n caffe_test python=2.7
$ source activate caffe_test
$ conda install -c conda-forge caffe
$ convert_imageset 
```
I get `convert_imageset: error while loading shared libraries: libprotobuf.so.14: cannot open shared object file: No such file or directory`

And similarly 
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/miniconda/envs/caffe_test/lib/python2.7/site-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/work/miniconda/envs/caffe_test/lib/python2.7/site-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libprotobuf.so.14: cannot open shared object file: No such file or directory

```

**Comment by dougalsutherland** [comment]
Those are because this recipe doesn't pin protobuf (a bug). Try `conda install -c conda-forge protobuf=3.2` to work around.

**Comment by JarnoRFB** [comment]
Unfortunately, that did not help either.

**Comment by dougalsutherland** [comment]
Oh, wait, it's looking for `.14`? That's protobuf 3.4 I think, but I'm confused by that.

**Comment by JarnoRFB** [comment]
Alright so after doing
`$ conda install -c conda-forge protobuf=3.4` `convert_imageset` works, but now `$ python -c "import caffe"` gives me 
```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/miniconda/envs/caffe_test/lib/python2.7/site-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/work/miniconda/envs/caffe_test/lib/python2.7/site-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: numpy.core.multiarray failed to import

```

Only after `$ conda install -c conda-forge numpy=1.13` this works as well, which is strange since conda should install the right numpy version in the first place.

**Comment by dougalsutherland** [comment]
That problem is because you have numpy installed from `defaults`, using MKL, and it's not compatible with the openblas-based numpy in conda-forge. You might have problems with scipy and similar too. See  https://github.com/conda-forge/conda-forge.github.io/issues/434

**Comment by JarnoRFB** [comment]
But how can I avoid this? Even if I set `conda-forge` to be highest priority by doing ´conda config --add channels conda-forge` I get exactly the same behavior. And shouldn't conda be able to figure out this things on its own, so the end user does not have to think about getting the right dependencies together. I have only known conda from this end user perspective so I am a bit confused.

**Comment by jakirkham** [comment]
Please try `conda install blas=*=openblas`.

**Comment by JarnoRFB** [comment]
The output of `$ conda install blas=*=openblas` is
```
# All requested packages already installed.
# packages in environment at /work/miniconda/envs/caffe_test:
#
blas                      1.1                    openblas    conda-forge
```

**Comment by jakirkham** [comment]
Can you please share the most recent result of `conda env export` and `conda list` (sadly the environment export doesn't show channels any more 😒)?

**Comment by JarnoRFB** [comment]
`$ conda env export` gives now
```
channels:
- conda-forge
- defaults
dependencies:
- asn1crypto=0.22.0=py27_0
- backports.shutil_get_terminal_size=1.0.0=py27_1
- backports_abc=0.5=py27_0
- bkcharts=0.2=py27_0
- blas=1.1=openblas
- bokeh=0.12.6=py27_0
- boost=1.64.0=py27_4
- boost-cpp=1.64.0=1
- bzip2=1.0.6=1
- ca-certificates=2017.7.27.1=0
- caffe=1.0.0rc4=py27_blas_openblas_203
- cairo=1.14.6=4
- certifi=2017.7.27.1=py27_0
- cffi=1.10.0=py27_0
- chardet=3.0.4=py27_0
- click=6.7=py27_0
- cloudpickle=0.4.0=py27_0
- cryptography=2.0.3=py27_0
- cycler=0.10.0=py27_0
- dask=0.15.2=py27_0
- dask-core=0.15.2=py27_0
- decorator=4.1.2=py27_0
- distributed=1.18.3=py27_0
- enum34=1.1.6=py27_1
- ffmpeg=3.2.4=1
- fontconfig=2.12.1=4
- freetype=2.7=1
- functools32=3.2.3.2=py27_1
- futures=3.0.5=py27_0
- gettext=0.19.7=1
- gflags=2.2.0=1
- giflib=5.1.4=0
- glib=2.51.4=0
- glog=0.3.5=0
- h5py=2.7.1=py27_1
- harfbuzz=1.3.4=2
- hdf5=1.8.18=0
- heapdict=1.0.0=py27_0
- icu=58.1=1
- idna=2.5=py27_0
- imageio=2.2.0=py27_0
- ipaddress=1.0.18=py27_0
- ipython=5.4.1=py27_0
- ipython_genutils=0.2.0=py27_0
- jasper=1.900.1=4
- jinja2=2.9.6=py27_0
- jpeg=9b=0
- leveldb=1.18=0
- libffi=3.2.1=3
- libiconv=1.14=4
- libpng=1.6.28=0
- libtiff=4.0.6=7
- libwebp=0.5.2=7
- libxml2=2.9.4=4
- lmdb=0.9.18=1
- locket=0.2.0=py27_1
- markupsafe=1.0=py27_0
- matplotlib=2.0.0=np112py27_2
- msgpack-python=0.4.8=py27_0
- ncurses=5.9=10
- networkx=1.11=py27_0
- numpy=1.12.1=py27_blas_openblas_200
- olefile=0.44=py27_0
- openblas=0.2.19=2
- opencv=3.2.0=np112py27_blas_openblas_203
- openssl=1.0.2l=0
- pandas=0.20.3=py27_1
- pango=1.40.3=3
- partd=0.3.8=py27_0
- pathlib2=2.3.0=py27_0
- pcre=8.39=0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pillow=4.2.1=py27_0
- pip=9.0.1=py27_0
- pixman=0.34.0=0
- prompt_toolkit=1.0.15=py27_0
- protobuf=3.4.0=py27_0
- psutil=5.2.2=py27_0
- ptyprocess=0.5.2=py27_0
- pycparser=2.18=py27_0
- pygments=2.2.0=py27_0
- pyopenssl=17.2.0=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=4.11.4=py27_2
- pysocks=1.6.7=py27_0
- python=2.7.13=1
- python-dateutil=2.6.1=py27_0
- python-gflags=2.0=py27_1
- python-leveldb=0.193=py27_0
- pytz=2017.2=py27_0
- pywavelets=0.5.2=np112py27_0
- pyyaml=3.12=py27_1
- qt=4.8.7=7
- readline=6.2=0
- requests=2.18.4=py27_1
- scandir=1.5=py27_1
- scikit-image=0.13.0=py27_1
- scipy=0.19.1=py27_blas_openblas_202
- setuptools=36.3.0=py27_0
- simplegeneric=0.8.1=py27_0
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_1
- six=1.10.0=py27_1
- snappy=1.1.6=1
- sortedcontainers=1.5.7=py27_0
- sqlite=3.13.0=1
- ssl_match_hostname=3.5.0.1=py27_1
- subprocess32=3.2.7=py27_0
- tblib=1.3.2=py27_0
- tk=8.5.19=2
- toolz=0.8.2=py27_0
- tornado=4.5.2=py27_0
- traitlets=4.3.2=py27_0
- urllib3=1.22=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- x264=20131217=3
- xz=5.2.3=0
- yaml=0.1.6=0
- zict=0.1.2=py27_0
- zlib=1.2.8=3
- libgfortran=3.0.0=1
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.5.0.1
  - ipython-genutils==0.2.0
  - prompt-toolkit==1.0.15
```

and `$ conda env list` gives
```
# packages in environment at /work/miniconda/envs/caffe_test:
#
asn1crypto                0.22.0                   py27_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                    py27_1    conda-forge
backports_abc             0.5                      py27_0    conda-forge
bkcharts                  0.2                      py27_0    conda-forge
blas                      1.1                    openblas    conda-forge
bokeh                     0.12.6                   py27_0    conda-forge
boost                     1.64.0                   py27_4    conda-forge
boost-cpp                 1.64.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
caffe                     1.0.0rc4        py27_blas_openblas_203  [blas_openblas]  conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2017.7.27.1              py27_0    conda-forge
cffi                      1.10.0                   py27_0    conda-forge
chardet                   3.0.4                    py27_0    conda-forge
click                     6.7                      py27_0    conda-forge
cloudpickle               0.4.0                    py27_0    conda-forge
cryptography              2.0.3                    py27_0    conda-forge
cycler                    0.10.0                   py27_0    conda-forge
dask                      0.15.2                   py27_0    conda-forge
dask-core                 0.15.2                   py27_0    conda-forge
decorator                 4.1.2                    py27_0    conda-forge
distributed               1.18.3                   py27_0    conda-forge
enum34                    1.1.6                    py27_1    conda-forge
ffmpeg                    3.2.4                         1    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
functools32               3.2.3.2                  py27_1    conda-forge
futures                   3.0.5                    py27_0    conda-forge
gettext                   0.19.7                        1    conda-forge
gflags                    2.2.0                         1    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.51.4                        0    conda-forge
glog                      0.3.5                         0    conda-forge
h5py                      2.7.1                    py27_1    conda-forge
harfbuzz                  1.3.4                         2    conda-forge
hdf5                      1.8.18                        0    conda-forge
heapdict                  1.0.0                    py27_0    conda-forge
icu                       58.1                          1    conda-forge
idna                      2.5                      py27_0    conda-forge
imageio                   2.2.0                    py27_0    conda-forge
ipaddress                 1.0.18                   py27_0    conda-forge
ipython                   5.4.1                    py27_0    conda-forge
ipython_genutils          0.2.0                    py27_0    conda-forge
jasper                    1.900.1                       4    conda-forge
jinja2                    2.9.6                    py27_0    conda-forge
jpeg                      9b                            0    conda-forge
leveldb                   1.18                          0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libtiff                   4.0.6                         7    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxml2                   2.9.4                         4    conda-forge
lmdb                      0.9.18                        1    conda-forge
locket                    0.2.0                    py27_1    conda-forge
markupsafe                1.0                      py27_0    conda-forge
matplotlib                2.0.0               np112py27_2    conda-forge
msgpack-python            0.4.8                    py27_0    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  1.11                     py27_0    conda-forge
numpy                     1.12.1          py27_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.44                     py27_0    conda-forge
openblas                  0.2.19                        2    conda-forge
opencv                    3.2.0           np112py27_blas_openblas_203  [blas_openblas]  conda-forge
openssl                   1.0.2l                        0    conda-forge
pandas                    0.20.3                   py27_1    conda-forge
pango                     1.40.3                        3    conda-forge
partd                     0.3.8                    py27_0    conda-forge
pathlib2                  2.3.0                    py27_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py27_0    conda-forge
pickleshare               0.7.4                    py27_0    conda-forge
pillow                    4.2.1                    py27_0    conda-forge
pip                       9.0.1                    py27_0    conda-forge
pixman                    0.34.0                        0    conda-forge
prompt_toolkit            1.0.15                   py27_0    conda-forge
protobuf                  3.4.0                    py27_0    conda-forge
psutil                    5.2.2                    py27_0    conda-forge
ptyprocess                0.5.2                    py27_0    conda-forge
pycparser                 2.18                     py27_0    conda-forge
pygments                  2.2.0                    py27_0    conda-forge
pyopenssl                 17.2.0                   py27_0    conda-forge
pyparsing                 2.2.0                    py27_0    conda-forge
pyqt                      4.11.4                   py27_2    conda-forge
pysocks                   1.6.7                    py27_0    conda-forge
python                    2.7.13                        1    conda-forge
python-dateutil           2.6.1                    py27_0    conda-forge
python-gflags             2.0                      py27_1    conda-forge
python-leveldb            0.193                    py27_0    conda-forge
pytz                      2017.2                   py27_0    conda-forge
pywavelets                0.5.2               np112py27_0    conda-forge
pyyaml                    3.12                     py27_1    conda-forge
qt                        4.8.7                         7    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.4                   py27_1    conda-forge
scandir                   1.5                      py27_1    conda-forge
scikit-image              0.13.0                   py27_1    conda-forge
scipy                     0.19.1          py27_blas_openblas_202  [blas_openblas]  conda-forge
setuptools                36.3.0                   py27_0    conda-forge
simplegeneric             0.8.1                    py27_0    conda-forge
singledispatch            3.4.0.3                  py27_0    conda-forge
sip                       4.18                     py27_1    conda-forge
six                       1.10.0                   py27_1    conda-forge
snappy                    1.1.6                         1    conda-forge
sortedcontainers          1.5.7                    py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
ssl_match_hostname        3.5.0.1                  py27_1    conda-forge
subprocess32              3.2.7                    py27_0    conda-forge
tblib                     1.3.2                    py27_0    conda-forge
tk                        8.5.19                        2    conda-forge
toolz                     0.8.2                    py27_0    conda-forge
tornado                   4.5.2                    py27_0    conda-forge
traitlets                 4.3.2                    py27_0    conda-forge
urllib3                   1.22                     py27_0    conda-forge
wcwidth                   0.1.7                    py27_0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
x264                      20131217                      3    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zict                      0.1.2                    py27_0    conda-forge
zlib                      1.2.8                         3    conda-forge

```

**Comment by jakirkham** [comment]
Sorry remind me what the error message is that you are getting now? Still this [one]( https://github.com/conda-forge/caffe-feedstock/issues/33#issuecomment-328517742 ) or something else?

**Comment by JarnoRFB** [comment]
Exactly, it's
```
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/work/miniconda/envs/caffe_test/lib/python2.7/site-packages/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/work/miniconda/envs/caffe_test/lib/python2.7/site-packages/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: numpy.core.multiarray failed to import
```
but only after doing `conda install -c conda-forge protobuf=3.4`.

**Comment by jakirkham** [comment]
What if you just run `python -c "import numpy.core.multiarray"`?

**Comment by JarnoRFB** [comment]
That works without error...

**Comment by jakirkham** [comment]
What about `python -c "from numpy.core.multiarray import dot"`? Also may want to run `echo $?` right after these commands to verify there is not a silent error.

**Comment by JarnoRFB** [comment]
Is result from `python -c "from numpy.core.multiarray import dot" | echo $?` is just `0`.

**Comment by jakirkham** [comment]
We are rebuilding with the latest `protobuf`. Once it is out, could you please recheck if this is still an issue?

**Comment by JarnoRFB** [comment]
Sure, when will it be out?

**Comment by jakirkham** [comment]
Should be out now.

**Comment by JarnoRFB** [comment]
Seems to work fine for environments with python 2.7! Was this intended to work with python 3 as well, because this still gives errors
`convert_imageset: error while loading shared libraries: libprotobuf.so.12: cannot open shared object file: No such file or directory
`

**Comment by dougalsutherland** [comment]
No, conda-forge still doesn't build caffe for python 3, so that's a problem with the caffe from `defaults`.

**Comment by JarnoRFB** [comment]
Alright, then I would consider this issue fixed. Thanks very much for your help and keep up the good work!

**Comment by jakirkham** [comment]
Thanks for testing. :)
